import os
import tempfile
from flask import Flask, render_template, request, jsonify
import yt_dlp

app = Flask(__name__)

# အသုံးပြုသူ ပေးပို့ထားသော YouTube Cookie စာသားများ
RAW_COOKIES = r"""
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com  TRUE  /  TRUE  1823243167  __Secure-3PSID  g.a000CQmxIckYJ7mnhZfaYDkkrprgpWyPxridHEARNZ41M9-UVMQyqmGxPfXQXmYD0C0O8PrxygACgYKAZUSARMSFQHGX2Miy8n698FEl0Qtz4Tx8YL-vxoVAUF8yKpZ4bMQSHBW58AO2b_EqUfr0076
#HttpOnly_.youtube.com  TRUE  /  TRUE  1821174532  __Secure-1PSIDTS  sidts-CjIBXMw41ajEtcMV8oVkWrRg_ZOuu74kT2ZgtU31B7d58sqlef02hNGyhcq5mBKLuYgfoBAA
.youtube.com  TRUE  /  TRUE  1823243167  __Secure-3PAPISID  tPDj3TT9IGEUJjn_/Arq4mVbqw6EM6jr4d
#HttpOnly_.youtube.com  TRUE  /  TRUE  1821174533  __Secure-3PSIDCC  AKEyXzUUN2FYQNqx38diLf7m1JXcfnUpXitDfAHTUNimOUwnZLTTKZNs4L5-SQVKdCi239DE2A
#HttpOnly_.youtube.com  TRUE  /  TRUE  1821174532  __Secure-3PSIDTS  sidts-CjIBXMw41ajEtcMV8oVkWrRg_ZOuu74kT2ZgtU31B7d58sqlef02hNGyhcq5mBKLuYgfoBAA
#HttpOnly_.youtube.com  TRUE  /  TRUE  1822812153  __Secure-YENID  17.YTE=k-qCrrtTAkvDPOdbwzMfSrbfRVQqLLWlQRt0LA-lAqYaF7UX8aS5vwGrfHK3agMOTDdBJKO79Nq9acKWMXJQKavAAjtT7cxlUkdpRNdDzykrkjl4W9DPwgzBFWO4AiMpLlbu_aHXFGSSM49h7hB23fpoD4cxH0pFBle7wp8dQ4LKNrh8iTowWU7WY9d4e9ZqxH9dcs10AGb9YuXjSveZhj3VufxY49Leuutl0O3I3uoZCRK17p5qEMJorRnNaaVQL91wUliTnCD5OvY5ayJBnd17zLltrXHqL4NZDbvM5cAGxFSlJszZ-HQa-O6y8KQOPIkOOMZEyxXDuCQJdYFiOw
#HttpOnly_.youtube.com  TRUE  /  TRUE  1823243746  LOGIN_INFO  AFmmF2swRQIhAMJLpctwzlRwzdCa6sm1JO7Vy9KkKjmRL9UKVivJWJz6AiAhh5jiwEXPGjApINf2u4wtYctkwThpSraFYXbYVvOHWA:QUQ3MjNmeWc3WkliYmtiWDR6eVRfSmJDeXlxOTRma2pKQ3Z1Z1FxZWdHTThOOHhObE85WFgxWklMZmgteFN6cFRoWUxLTEE3Q2VMTGs4bmNieF9nOGxIYThCa3lJZmZJYlJzN3pKS096bk9CT0lWdWZsVWtnNFUtVGRBN0VTWHljNGNqb3VqbDhnekRzU3VZeHBQVHlwOE9YSGpYS0x3aG5B
.youtube.com  TRUE  /  TRUE  1824198530  PREF  tz=Asia.Rangoon&f4=4000000&f7=100
"""

def prepare_cookie_file():
    """Cookie စာသားများကို yt-dlp ဖတ်နိုင်သော စံချိန်မီ TAB-separated Netscape format သို့ ပြောင်းလဲပေးခြင်း"""
    parsed_lines = ["# Netscape HTTP Cookie File"]
    
    for line in RAW_COOKIES.strip().splitlines():
        line = line.strip()
        if not line or line.startswith("# http"):
            continue
            
        # #HttpOnly_ ပါပါက ဖြုတ်ပေးပြီး Domain အမှန်အတိုင်း ပြင်ခြင်း
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_"):]
            
        # Space များကို TAB (\t) သို့ ပြောင်းပေးခြင်း
        parts = line.split()
        if len(parts) >= 7:
            domain, flag, path, secure, expiration, name = parts[:6]
            value = " ".join(parts[6:])
            parsed_lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}")
            
    temp_dir = tempfile.gettempdir()
    cookie_path = os.path.join(temp_dir, 'yt_formatted_cookies.txt')
    with open(cookie_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(parsed_lines) + "\n")
    return cookie_path

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/download', methods=['POST'])
def download():
    # downloads folder မရှိပါက အလိုအလျောက် ဖန်တီးပေးခြင်း (Server Crash မဖြစ်အောင် ကာကွယ်ခြင်း)
    os.makedirs('downloads', exist_ok=True)

    data = request.json or request.form
    url = data.get('url')
    choice = data.get('choice', 'mp3')

    if not url:
        return jsonify({'status': 'error', 'message': 'YouTube URL ထည့်သွင်းပါ'}), 400

    ydl_opts = {
        'format': 'bestaudio/best' if choice == 'mp3' else 'bestvideo+bestaudio/best',
        'outtmpl': 'downloads/%(title)s.%(ext)s',
        'quiet': True,
        'no_warnings': True,
        'nocheckcertificate': True,
        'geo_bypass': True,
        'socket_timeout': 30,
        'extractor_args': {
            'youtube': {
                'player_client': ['android', 'ios', 'mweb', 'web']
            }
        }
    }

    # Format ပြုလုပ်ပြီးသား Cookie ဖိုင်ကို ညွှန်ပေးခြင်း
    cookie_path = prepare_cookie_file()
    if cookie_path:
        ydl_opts['cookiefile'] = cookie_path

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            filename = ydl.prepare_filename(info)
            return jsonify({
                'status': 'success',
                'title': info.get('title'),
                'file': filename
            })
    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
